#!/usr/bin/env python3
"""Batch G: trained tabular RL baseline + baseline pipeline wiring + proposer
reset + UNKNOWN/topology fail-closed contracts. Offline (emulated), no OTA."""

import json
import os
import tempfile
import unittest

from decision.rl_controller import (
    RLTrainingConfig, train_tabular_policy, load_artifact, save_artifact,
    get_trained_policy, RLArtifactError, _default_artifact_path,
)


class TrainedRLPolicyTest(unittest.TestCase):
    def test_training_is_reproducible(self):
        a = train_tabular_policy(RLTrainingConfig())
        b = train_tabular_policy(RLTrainingConfig())
        self.assertEqual(a.digest, b.digest)
        self.assertEqual(a.policy, b.policy)

    def test_digest_is_canonical_sha256(self):
        a = train_tabular_policy(RLTrainingConfig())
        self.assertTrue(a.digest.startswith("rlpolicy-sha256-"))
        # 64 hex chars after the prefix
        self.assertEqual(len(a.digest.split("sha256-")[1]), 64)

    def test_provenance_records_training(self):
        a = train_tabular_policy(RLTrainingConfig())
        for k in ("algorithm", "learned", "config", "env_digest", "n_episodes"):
            self.assertIn(k, a.provenance)
        self.assertTrue(a.provenance["learned"])
        self.assertIn("q_learning", a.provenance["algorithm"])

    def test_policy_is_learned_not_handcrafted(self):
        # the learned policy responds monotonically to deficit and caps near the
        # I1 bound (3 dB) - an emergent optimum, not a fixed step table.
        cfg = RLTrainingConfig()
        a = train_tabular_policy(cfg)
        small = a.action_for_deficit(0.3, cfg)
        big = a.action_for_deficit(6.0, cfg)
        self.assertLessEqual(small, big)
        self.assertLessEqual(big, cfg.i1_power_bound_db + 1e-9)

    def test_artifact_roundtrip_and_reproduction(self):
        cfg = RLTrainingConfig()
        a = train_tabular_policy(cfg)
        with tempfile.TemporaryDirectory() as tmp:
            p = os.path.join(tmp, "policy.json")
            save_artifact(a, p)
            b = load_artifact(p, cfg=cfg, verify_reproduction=True)
            self.assertEqual(a.digest, b.digest)

    def test_corrupted_policy_is_rejected(self):
        cfg = RLTrainingConfig()
        a = train_tabular_policy(cfg)
        with tempfile.TemporaryDirectory() as tmp:
            p = os.path.join(tmp, "policy.json")
            save_artifact(a, p)
            with open(p) as fh:
                d = json.load(fh)
            d["policy"]["0"] = 99.0            # tamper a policy entry
            with open(p, "w") as fh:
                json.dump(d, fh)
            with self.assertRaises(RLArtifactError):
                load_artifact(p, cfg=cfg)

    def test_tampered_digest_is_rejected(self):
        cfg = RLTrainingConfig()
        a = train_tabular_policy(cfg)
        with tempfile.TemporaryDirectory() as tmp:
            p = os.path.join(tmp, "policy.json")
            save_artifact(a, p)
            with open(p) as fh:
                d = json.load(fh)
            d["digest"] = "rlpolicy-sha256-" + "0" * 64
            with open(p, "w") as fh:
                json.dump(d, fh)
            with self.assertRaises(RLArtifactError):
                load_artifact(p, cfg=cfg)

    def test_config_mismatch_is_rejected(self):
        cfg = RLTrainingConfig()
        a = train_tabular_policy(cfg)
        with tempfile.TemporaryDirectory() as tmp:
            p = os.path.join(tmp, "policy.json")
            save_artifact(a, p)
            other = RLTrainingConfig(n_episodes=cfg.n_episodes + 1)
            with self.assertRaises(RLArtifactError):
                load_artifact(p, cfg=other)

    def test_checked_in_artifact_validates(self):
        # the packaged artifact (generated by python -m decision.rl_controller)
        path = _default_artifact_path()
        if os.path.isfile(path):
            tp = load_artifact(path, cfg=RLTrainingConfig(),
                               verify_reproduction=True)
            self.assertTrue(tp.provenance["learned"])


class _EmuMixin:
    def _coord(self, seed=13):
        # legacy generic-wiring coordinator: single-UE-per-cell (2-UE), passed
        # EXPLICITLY so this fixture is independent of the default topology (which
        # now follows the provisioned real UE set, not a fixed count).
        from experiments.emulation import build_emulated_coordinator
        from experiments.topology import two_ue_topology
        return build_emulated_coordinator(seed=seed, tau_trial_s=0.1,
                                          topology=two_ue_topology())


class BaselineWiringTest(_EmuMixin, unittest.TestCase):
    def test_baselines_are_registered_backends(self):
        c, ch = self._coord()
        try:
            names = c.llm_manager.get_available_names()
            for m in ("rule_based", "score_heuristic", "rl_controller"):
                self.assertIn(f"baseline:{m}", names)
                self.assertTrue(c.set_llm_backend(f"baseline:{m}"))
        finally:
            c.stop()

    def test_rl_backend_uses_trained_policy(self):
        c, ch = self._coord()
        try:
            c.set_llm_backend("baseline:rl_controller")
            b = c.llm_manager.dynamic_backends["baseline:rl_controller"]
            self.assertTrue(b.learned)
            self.assertTrue(b.policy_digest.startswith("rlpolicy-sha256-"))
        finally:
            c.stop()

    def test_all_methods_share_safety_executor(self):
        from experiments.runner import ExperimentRunner
        methods = ["rule_based", "score_heuristic", "rl_controller",
                   "llm_no_history", "llm_with_history"]
        c, ch = self._coord()
        try:
            exec_id = id(c.executor)
            with tempfile.TemporaryDirectory() as tmp:
                r = ExperimentRunner(coordinator=c, output_dir=tmp,
                                     kpi_interval_s=0.0, steps_per_phase=1)
                r.channel_model = ch
                steps, eps = r.run_live(methods, trials=1)
            by = {}
            for e in eps:
                by[e.method] = by.get(e.method, 0) + 1
            # every method produced records (none silently skipped)...
            self.assertEqual(set(by), set(methods))
            # ...through the SAME executor object
            self.assertEqual(id(c.executor), exec_id)
        finally:
            c.stop()

    def test_missing_baseline_fails_not_skips(self):
        from experiments.runner import ExperimentRunner

        class _NoBaseline:
            executor = object()
            ue_collector = type("C", (), {"simulation_mode": False,
                                          "emulated": True})()

            def set_llm_backend(self, name):
                return False   # no baseline backend available

            def set_probe_config(self, pc):
                pass

            def _active_model_id(self):
                return "llm"
        r = ExperimentRunner(coordinator=_NoBaseline(), kpi_interval_s=0.0)
        with self.assertRaises(RuntimeError):
            r._configure_method("rule_based")   # fail closed, not skip

    def test_run_live_restores_entry_backend(self):
        from experiments.runner import ExperimentRunner
        c, ch = self._coord()
        try:
            entry = c.llm_manager.active_backend_name()
            with tempfile.TemporaryDirectory() as tmp:
                r = ExperimentRunner(coordinator=c, output_dir=tmp,
                                     kpi_interval_s=0.0, steps_per_phase=1)
                r.channel_model = ch
                r.run_live(["rule_based", "llm_with_history"], trials=1)
            self.assertEqual(c.llm_manager.active_backend_name(), entry)
        finally:
            c.stop()

    def test_llm_method_does_not_inherit_baseline(self):
        from experiments.runner import ExperimentRunner
        c, ch = self._coord()
        try:
            r = ExperimentRunner(coordinator=c, kpi_interval_s=0.0)
            r.channel_model = ch
            r._llm_backend_name = r._active_model_key(c)
            r._configure_method("rule_based")
            self.assertTrue(
                c.llm_manager.active_backend_name().startswith("baseline:"))
            r._configure_method("llm_with_history")
            self.assertFalse(
                c.llm_manager.active_backend_name().startswith("baseline:"))
        finally:
            c.stop()

    def test_prompt_enumerates_configured_ues(self):
        # a 3-UE coordinator's system prompt enumerates ue1/ue2/ue3
        c, ch = self._coord()
        try:
            c.llm_manager.ue_ids = ["ue1", "ue2", "ue3"]
            c.llm_manager.ue_serving = {"ue1": "gnb1", "ue2": "gnb1",
                                        "ue3": "gnb2"}
            sp = c.llm_manager.get_system_prompt()
            for ue in ("ue1", "ue2", "ue3"):
                self.assertIn(ue, sp)
            self.assertIn("SHARED", sp)   # shared-cell disclosure
        finally:
            c.stop()


class ThreeUEEmulatedTest(unittest.TestCase):
    def _coord3(self, seed=3):
        from experiments.emulation import build_emulated_coordinator
        from experiments.topology import three_ue_shared_topology
        t = three_ue_shared_topology()
        c, ch = build_emulated_coordinator(seed=seed, tau_trial_s=0.1,
                                           topology=t)
        return c, ch, t

    def test_three_ue_emulated_collector_enumerates(self):
        c, ch, t = self._coord3()
        try:
            m = c.ue_collector.collect_all()
            self.assertEqual(set(m), {"ue1", "ue2", "ue3"})
            self.assertEqual(c.ue_serving_gnb["ue2"], "gnb1")  # shared cell
        finally:
            c.stop()

    def test_emulated_default_follows_provisioned_set(self):
        # UE count is variable: build_emulated_coordinator() with NO topology
        # defaults to the CURRENTLY PROVISIONED real UE set (config-derived), NOT
        # a fixed 3-UE assumption. On the default config that is UE1+UE2 both on
        # gNB1 (a 2-UE SHARED cell); the unprovisioned logical UE3 is EXCLUDED and
        # would join automatically once provisioned.
        from experiments.emulation import build_emulated_coordinator
        c, ch = build_emulated_coordinator(seed=1, tau_trial_s=0.1)
        try:
            self.assertEqual(set(c.ue_collector.collect_all()),
                             {"ue1", "ue2"})
            self.assertEqual(c.ue_serving_gnb["ue1"], "gnb1")
            self.assertEqual(c.ue_serving_gnb["ue2"], "gnb1")   # shared with ue1
            self.assertNotIn("ue3", c.ue_serving_gnb)           # unprovisioned
        finally:
            c.stop()

    def test_scheduler_action_has_verified_readback(self):
        # WITH a KPI probe (emulated efficacy): truthful readback AND a measured,
        # correctly-signed KPI effect => qualified. The restore is verified and
        # the executor is not latched. OTA efficacy is still NOT proven.
        c, ch, t = self._coord3()
        try:
            ch.sigma = 0.0
            probe = lambda: c.ue_collector.get_throughput_all().get("ue1")
            q = c.executor.qualify_scheduler_priority(
                "gnb1", rnti=t.rnti("ue1"), kpi_probe=probe)
            self.assertTrue(q["readback_matches"])
            self.assertFalse(q["is_no_op"])       # proven non-no-op
            self.assertTrue(q["restored"])
            self.assertTrue(q["readback_qualified"])
            self.assertTrue(q["kpi_effect_verified"])   # measured KPI effect
            self.assertTrue(q["qualified"])
            self.assertEqual(q["canonical_command"], "ci sched_prio")
            self.assertFalse(q["hw_efficacy_verified"])  # emulated != OTA
            self.assertFalse(c.executor.is_latched)
        finally:
            c.stop()

    def test_scheduler_qualification_without_probe_is_not_qualified(self):
        # NO kpi_probe (hardware readback-only): the code path is proven
        # (readback_qualified) but scheduling EFFICACY is unverified, so the axis
        # is NOT qualified and hardware efficacy stays unverified.
        c, ch, t = self._coord3()
        try:
            q = c.executor.qualify_scheduler_priority("gnb1", rnti=t.rnti("ue1"))
            self.assertTrue(q["readback_qualified"])   # code path proven
            self.assertFalse(q["kpi_effect_verified"])  # no probe -> no KPI proof
            self.assertFalse(q["qualified"])            # efficacy unverified
            self.assertFalse(q["hw_efficacy_verified"])
            self.assertFalse(c.executor.is_latched)     # clean restore
        finally:
            c.stop()

    def test_scheduler_qualification_false_write_restores_unqualified(self):
        # AMBIGUOUS write that REPORTS failure: the finally still attempts the
        # trusted-original restore (a False write may have partially applied);
        # the axis is unqualified and the baseline is left intact.
        c, ch, t = self._coord3()
        try:
            c.executor.set_sched_priority = lambda *a, **k: False
            q = c.executor.qualify_scheduler_priority("gnb1", rnti=t.rnti("ue1"))
            self.assertTrue(q["write_attempted"])
            self.assertFalse(q["write_ok"])
            self.assertFalse(q["readback_qualified"])
            self.assertFalse(q["qualified"])
        finally:
            c.stop()

    def test_scheduler_qualification_raising_write_restores(self):
        # AMBIGUOUS write that RAISES: caught, restore attempted + verified, axis
        # unqualified, no latch (baseline restored).
        c, ch, t = self._coord3()
        try:
            orig_set = c.executor.set_sched_priority
            calls = {"n": 0}

            def _raise_first(gnb, w, rnti=None):
                calls["n"] += 1
                if calls["n"] == 1:
                    raise RuntimeError("write boom (ambiguous applied)")
                return orig_set(gnb, w, rnti=rnti)   # restore applies
            c.executor.set_sched_priority = _raise_first
            q = c.executor.qualify_scheduler_priority("gnb1", rnti=t.rnti("ue1"))
            self.assertTrue(q["write_attempted"])
            self.assertFalse(q["write_ok"])
            self.assertIn("raised", q.get("error", ""))
            self.assertTrue(q["restored"])          # restored after ambiguous write
            self.assertFalse(q["qualified"])
            self.assertFalse(c.executor.is_latched)
        finally:
            c.stop()

    def test_scheduler_qualification_restore_exception_latches(self):
        # RESTORE write RAISES: caught, executor latches (fail closed), axis
        # unqualified.
        c, ch, t = self._coord3()
        try:
            calls = {"n": 0}
            orig_set = c.executor.set_sched_priority

            def _raise_restore(gnb, w, rnti=None):
                calls["n"] += 1
                if calls["n"] == 1:
                    return orig_set(gnb, w, rnti=rnti)   # test write applies
                raise RuntimeError("restore boom")
            c.executor.set_sched_priority = _raise_restore
            q = c.executor.qualify_scheduler_priority("gnb1", rnti=t.rnti("ue1"))
            self.assertFalse(q["restored"])
            self.assertFalse(q["qualified"])
            self.assertTrue(c.executor.is_latched)   # FAIL CLOSED
        finally:
            c.stop()

    def test_scheduler_qualification_no_baseline_refuses_before_write(self):
        # NO trusted restore baseline (get_sched_priority is unobservable/None):
        # refuse BEFORE any write -> zero write, unqualified, and NO latch
        # (nothing was touched).
        c, ch, t = self._coord3()
        try:
            c.executor.get_sched_priority = lambda *a, **k: None
            writes = []
            orig_set = c.executor.set_sched_priority
            c.executor.set_sched_priority = (
                lambda *a, **k: writes.append(1) or orig_set(*a, **k))
            q = c.executor.qualify_scheduler_priority("gnb1", rnti=t.rnti("ue1"))
            self.assertFalse(q["write_attempted"])   # refused before any write
            self.assertFalse(q["readback_qualified"])
            self.assertFalse(q["qualified"])
            self.assertEqual(writes, [])             # ZERO writes
            self.assertFalse(c.executor.is_latched)  # nothing touched -> no latch
        finally:
            c.stop()

    # -- P0-18 shared-cell contention counterexamples (deterministic) -------- #

    def test_shared_cell_contention_shifts_share_deterministically(self):
        # sigma=0 => deterministic: raising UE1's scheduler priority on the
        # SHARED cell improves UE1's KPI, reduces UE2's share, keeps the cell
        # allocation bounded by the cell capacity, and leaves UE3 (a different
        # cell, no cross-cell coupling) unchanged.
        c, ch, t = self._coord3()
        try:
            ch.sigma = 0.0
            base = c.ue_collector.collect_all()
            b1 = base["ue1"].throughput_mbps
            b2 = base["ue2"].throughput_mbps
            b3 = base["ue3"].throughput_mbps
            capacity = b1 + b2                     # bounded shared-cell resource
            self.assertTrue(c.executor.set_sched_priority(
                "gnb1", 4.0, rnti=t.rnti("ue1")))  # UE1 priority up
            after = c.ue_collector.collect_all()
            a1 = after["ue1"].throughput_mbps
            a2 = after["ue2"].throughput_mbps
            a3 = after["ue3"].throughput_mbps
            self.assertGreater(a1, b1)             # UE1 KPI improves
            self.assertLess(a2, b2)                # UE2 share reduced
            self.assertLessEqual(a1 + a2, capacity + 1e-6)   # cell share bounded
            self.assertAlmostEqual(a3, b3, places=6)         # UE3 unchanged
        finally:
            c.stop()

    def test_shared_cell_noop_priority_leaves_allocation_unchanged(self):
        # NO-OP counterexample: re-applying the PF-neutral weight UE1 already
        # holds changes NOTHING; equal weights split the cell evenly.
        from executor.oai_executor import PRIO_NEUTRAL
        c, ch, t = self._coord3()
        try:
            ch.sigma = 0.0
            base = c.ue_collector.collect_all()
            self.assertTrue(c.executor.set_sched_priority(
                "gnb1", PRIO_NEUTRAL, rnti=t.rnti("ue1")))   # no real change
            after = c.ue_collector.collect_all()
            for ue in ("ue1", "ue2", "ue3"):
                self.assertAlmostEqual(after[ue].throughput_mbps,
                                       base[ue].throughput_mbps, places=6)
            # equal (neutral) weights => the two shared UEs split evenly
            self.assertAlmostEqual(after["ue1"].throughput_mbps,
                                   after["ue2"].throughput_mbps, places=6)
        finally:
            c.stop()

    def test_scheduler_qualification_restore_failure_latches(self):
        # RESTORE counterexample: if the temporary qualification write cannot be
        # readback-verified as restored, the executor FAILS CLOSED (latches) and
        # the axis is NOT qualified. Here the restore write is silently dropped.
        c, ch, t = self._coord3()
        try:
            calls = {"n": 0}
            orig_set = c.executor.set_sched_priority

            def _drop_restore(gnb, weight, rnti=None):
                calls["n"] += 1
                if calls["n"] == 1:
                    return orig_set(gnb, weight, rnti=rnti)   # test write applies
                return True         # restore write reports OK but is NOT applied
            c.executor.set_sched_priority = _drop_restore
            self.assertFalse(c.executor.is_latched)   # property, not a call
            q = c.executor.qualify_scheduler_priority("gnb1", rnti=t.rnti("ue1"))
            self.assertFalse(q["restored"])           # restore unverified
            self.assertFalse(q["qualified"])          # not qualified
            self.assertTrue(c.executor.is_latched)    # FAIL CLOSED
        finally:
            c.stop()

    def test_paired_reset_fault_causes_zero_method_execution(self):
        from experiments.paired_runner import (
            PairedBlockRunner, DataOrigin, PairedResetError)
        c, ch, t = self._coord3(seed=7)
        try:
            # inject an executor restore that FAILS read-back verification
            c.executor.restore = lambda snap: False
            r = PairedBlockRunner(["rule_based", "llm_with_history"], topology=t,
                                  n_blocks=1, master_seed=7, trials_per_block=1,
                                  steps_per_phase=1,
                                  data_origin=DataOrigin.EMULATED_PIPELINE,
                                  coordinator=c)
            r.channel_model = ch
            calls = []
            orig = r._run_method_in_block
            r._run_method_in_block = (
                lambda *a, **k: (calls.append(1), orig(*a, **k))[1])
            with self.assertRaises(PairedResetError):
                r.run()
            self.assertEqual(calls, [])   # ZERO method execution on failed reset
        finally:
            c.stop()


class FailClosedProposerTest(_EmuMixin, unittest.TestCase):
    def _prompt(self, ue_states):
        return ("=== NEW INTENT (to be evaluated) ===\n"
                '{"target":{"target_value":8.0}}\n'
                "=== CURRENT NETWORK STATE ===\n"
                + json.dumps({"ue_states": ue_states}))

    def test_unknown_throughput_is_not_zero_deficit(self):
        c, ch = self._coord()
        try:
            c.set_llm_backend("baseline:rule_based")
            b = c.llm_manager.dynamic_backends["baseline:rule_based"]
            resp = b.generate(self._prompt(
                {"ue1": {"throughput_mbps": None, "serving_bs": "bs1"}}), "")
            d = json.loads(resp.content)
            # fail-closed: UNKNOWN telemetry -> low confidence, not silent 0
            self.assertLessEqual(d["confidence"], 0.2)
        finally:
            c.stop()

    def test_missing_serving_bs_is_not_index_guessed(self):
        c, ch = self._coord()
        try:
            c.set_llm_backend("baseline:rule_based")
            b = c.llm_manager.dynamic_backends["baseline:rule_based"]
            resp = b.generate(self._prompt(
                {"ue1": {"throughput_mbps": 3.0}}), "")   # no serving_bs
            self.assertFalse(resp.success)   # backend errors, no index guess
        finally:
            c.stop()


if __name__ == "__main__":
    unittest.main()
