"""The Agent's coordination layer: the T x C board, and who searches it.

This package is the part of the Agent (the role the rApp used to carry) that
sits *above* one Kernel case.  A case applies one frozen candidate, judges it
and settles it; this layer says which candidate to try next and remembers what
each one did to the **whole** intent set and the **whole** action set.

Two sittings live here.

* :mod:`assurance.coordination.tc` and :mod:`assurance.coordination.agents` are
  the current one: the target contract ``T`` (rows), the joint control
  candidates ``C`` (columns), the :class:`~assurance.coordination.tc.Grid` a
  trial fills one column of, and the **Target / Control / Trajectory** agents
  -- one model call per decision, each on a model the operator chose -- plus
  the internal-monolith, basic-monolith and deterministic comparison arms.
* :mod:`assurance.coordination.board`, :mod:`~assurance.coordination.priorities`
  and :mod:`~assurance.coordination.search` are the previous whole-state pair
  sitting.  They stay in the tree and keep their tests; the new sitting does
  not depend on them.

Nothing here decides a verdict, issues a permit or reaches an actuator.  Every
input is read out of the Kernel's own trial record and the Write Gateway's own
evidence, and every output is either a record or the name of something the
Kernel may still refuse.

The vocabulary is general in the number of intents, owners, UEs, action axes
and targets: every dimension is read from its argument, never counted in code.
"""

from assurance.coordination.agents import (  # noqa: F401
    DEFAULT_ROLE_MODELS_FILENAME,
    DETERMINISTIC,
    METHOD_BASIC_MONOLITH,
    METHOD_DETERMINISTIC,
    METHOD_INTERNAL_MONOLITH,
    METHOD_THREE_AGENT,
    METHOD_THREE_AGENT_COVERAGE,
    COVERAGE_METHODS,
    CONTROL_COVERAGE_SYSTEM_PROMPT,
    METHODS,
    PHASES,
    PHASE_CLARIFICATION,
    PHASE_FORMATION,
    PHASE_INTAKE,
    PHASE_RETENTION,
    PHASE_SELECTION,
    PROMPT_SOURCE_HEADINGS,
    ROLE_CONTROL,
    ROLE_MODELS_SCHEMA,
    ROLE_MONOLITH,
    ROLE_TARGET,
    ROLE_TRAJECTORY,
    ROLES,
    SYSTEM_PROMPTS,
    AnswerRefused,
    BasicInputs,
    CallRecord,
    ClarificationNeeded,
    DecisionUnavailable,
    ControlInputs,
    MonolithFormInputs,
    RoleAgents,
    RoleModels,
    ScriptedResolver,
    TargetInputs,
    TrajectoryInputs,
    budget_terms_in,
    default_resolver,
    load_role_models_file,
    save_role_models_file,
)
from assurance.coordination.intake import (  # noqa: F401
    DEFAULT_OBSERVATION_RULES,
    STATISTIC_RATIO,
    GENERATION_DEFAULTS,
    REQUIRED_SITTING_SETTINGS,
    SITTING,
    GenerationOptions,
    IntakeChecklist,
    KpiObservationRule,
    ObservationRules,
    choose_from_calibration,
    load_latency_calibration,
    merge_answers,
)
from assurance.coordination.predictor import (  # noqa: F401
    DEFAULT_UNCERTAINTY,
    JointEffectPredictor,
    NetworkState,
    PredictedKpi,
)
from assurance.coordination.tc import (  # noqa: F401
    CONTROL_CANDIDATES_SCHEMA,
    COST_RULE_SUM_W_Q2,
    COST_RULE_NORMALIZED_CONCESSION,
    DEADLINE_CONCESSION_SUFFIX,
    DEADLINE_RATIO_UNIT,
    KPI_DEADLINE_RATIO,
    KPI_GOODPUT,
    KPI_SERVING_CELL,
    SUPPORTED_KPIS,
    DEFAULT_TIE_BREAK,
    EPISODE_SCHEMA,
    FAIL,
    PASS,
    RULE_BASELINE,
    RULE_KEEP_CURRENT,
    TARGET_CONTRACT_SCHEMA,
    TERMINATION_REASONS,
    UNKNOWN,
    UNSELECTED_FUNCTION_RULES,
    Authorization,
    AuthorizedRequirement,
    BasicDecision,
    BestAttained,
    CompatibilityRules,
    ControlCandidate,
    ControlCandidates,
    ControlValidationError,
    EpisodeRecord,
    AXIS_SCOPE_KINDS,
    FUNCTION_NAMING,
    FunctionCatalog,
    FunctionSelection,
    FunctionSpec,
    Grid,
    Intent,
    JointCondition,
    Observation,
    PolicyField,
    Preference,
    Requirement,
    Target,
    TargetContract,
    TargetValidationError,
    TrajectoryDecision,
    Trial,
    concession_of,
    cost_of,
    preference_key,
    deterministic_configuration,
    deterministic_controls,
    catalog_product_controls,
    cover_controls,
    deterministic_function_moves,
    deterministic_targets,
    deterministic_trajectory,
    expand_targets,
    omega_or_sparse,
    intent_from_sentence,
    judge,
    judge_target,
    kpi_gaps,
    axis_kind,
    kpi_key,
    scope_for,
    observed_best,
    omega_contract,
    shown_target_ids,
    OMEGA_ONLY_PREFIX,
    omega_targets,
    translate_functions,
    validate_control_candidates,
    control_kpi_associations,
    model_effect_evidence,
    validate_target_contract,
    verdict_of,
)
from assurance.coordination.board import (  # noqa: F401
    ActionState,
    ActionVerification,
    Board,
    IntentState,
    OutcomeKind,
    PairProvenance,
    StatePair,
    action_states_from_candidate,
    derive_state_pair,
    intent_states_from_verdicts,
)
from assurance.coordination.priorities import (  # noqa: F401
    ActionPriorityCoordinator,
    IntentPriorityCoordinator,
    PairComparator,
    PriorityPolicy,
)
from assurance.coordination.search import (  # noqa: F401
    ActionAxisView,
    BoardSearcher,
    CandidateView,
    IntentView,
    SearchDecision,
    TerminationReason,
)

__all__ = [
    # -- the T x C sitting -------------------------------------------------
    "AnswerRefused",
    "Authorization",
    "COST_RULE_SUM_W_Q2",
    "COST_RULE_NORMALIZED_CONCESSION",
    "CompatibilityRules",
    "ClarificationNeeded",
    "DecisionUnavailable",
    "ControlValidationError",
    "DEADLINE_CONCESSION_SUFFIX",
    "DEADLINE_RATIO_UNIT",
    "DEFAULT_OBSERVATION_RULES",
    "DEFAULT_TIE_BREAK",
    "KPI_DEADLINE_RATIO",
    "KPI_GOODPUT",
    "KPI_SERVING_CELL",
    "STATISTIC_RATIO",
    "SUPPORTED_KPIS",
    "DEFAULT_UNCERTAINTY",
    "AXIS_SCOPE_KINDS",
    "FUNCTION_NAMING",
    "FunctionCatalog",
    "FunctionSelection",
    "FunctionSpec",
    "GENERATION_DEFAULTS",
    "GenerationOptions",
    "IntakeChecklist",
    "JointCondition",
    "JointEffectPredictor",
    "KpiObservationRule",
    "NetworkState",
    "Observation",
    "ObservationRules",
    "PHASES",
    "PHASE_CLARIFICATION",
    "PHASE_FORMATION",
    "PHASE_INTAKE",
    "PHASE_RETENTION",
    "PHASE_SELECTION",
    "PROMPT_SOURCE_HEADINGS",
    "PolicyField",
    "PredictedKpi",
    "REQUIRED_SITTING_SETTINGS",
    "RULE_BASELINE",
    "RULE_KEEP_CURRENT",
    "SITTING",
    "UNSELECTED_FUNCTION_RULES",
    "choose_from_calibration",
    "cost_of",
    "preference_key",
    "catalog_product_controls",
    "cover_controls",
    "deterministic_function_moves",
    "expand_targets",
    "omega_or_sparse",
    "judge_target",
    "kpi_gaps",
    "load_latency_calibration",
    "merge_answers",
    "observed_best",
    "omega_contract",
    "shown_target_ids",
    "OMEGA_ONLY_PREFIX",
    "omega_targets",
    "translate_functions",
    "AuthorizedRequirement",
    "BasicDecision",
    "BasicInputs",
    "BestAttained",
    "CONTROL_CANDIDATES_SCHEMA",
    "CallRecord",
    "ControlCandidate",
    "ControlCandidates",
    "ControlInputs",
    "DEFAULT_ROLE_MODELS_FILENAME",
    "DETERMINISTIC",
    "EPISODE_SCHEMA",
    "EpisodeRecord",
    "FAIL",
    "Grid",
    "Intent",
    "METHODS",
    "METHOD_BASIC_MONOLITH",
    "METHOD_DETERMINISTIC",
    "METHOD_INTERNAL_MONOLITH",
    "METHOD_THREE_AGENT",
    "METHOD_THREE_AGENT_COVERAGE",
    "COVERAGE_METHODS",
    "CONTROL_COVERAGE_SYSTEM_PROMPT",
    "MonolithFormInputs",
    "PASS",
    "Preference",
    "ROLES",
    "ROLE_CONTROL",
    "ROLE_MODELS_SCHEMA",
    "ROLE_MONOLITH",
    "ROLE_TARGET",
    "ROLE_TRAJECTORY",
    "Requirement",
    "RoleAgents",
    "RoleModels",
    "SYSTEM_PROMPTS",
    "ScriptedResolver",
    "TARGET_CONTRACT_SCHEMA",
    "TERMINATION_REASONS",
    "Target",
    "TargetContract",
    "TargetInputs",
    "TargetValidationError",
    "TrajectoryDecision",
    "TrajectoryInputs",
    "Trial",
    "UNKNOWN",
    "budget_terms_in",
    "concession_of",
    "default_resolver",
    "deterministic_configuration",
    "deterministic_controls",
    "deterministic_targets",
    "deterministic_trajectory",
    "intent_from_sentence",
    "judge",
    "axis_kind",
    "kpi_key",
    "scope_for",
    "load_role_models_file",
    "save_role_models_file",
    "validate_control_candidates",
    "control_kpi_associations",
    "model_effect_evidence",
    "validate_target_contract",
    "verdict_of",
    # -- the previous whole-state pair sitting, kept for its own tests ------
    "ActionAxisView",
    "ActionPriorityCoordinator",
    "ActionState",
    "ActionVerification",
    "Board",
    "BoardSearcher",
    "CandidateView",
    "IntentPriorityCoordinator",
    "IntentState",
    "IntentView",
    "OutcomeKind",
    "PairComparator",
    "PairProvenance",
    "PriorityPolicy",
    "SearchDecision",
    "StatePair",
    "TerminationReason",
    "action_states_from_candidate",
    "derive_state_pair",
    "intent_states_from_verdicts",
]
